export const API_V1_CATEGORY_LIST = "API_V1_CATEGORY_LIST"
export const API_V1_CATEGORY_LIST_SUCCEEDED = "API_V1_CATEGORY_LIST_SUCCEEDED"
export const API_V1_CATEGORY_LIST_FAILED = "API_V1_CATEGORY_LIST_FAILED"
export const API_V1_CATEGORY_CREATE = "API_V1_CATEGORY_CREATE"
export const API_V1_CATEGORY_CREATE_SUCCEEDED =
  "API_V1_CATEGORY_CREATE_SUCCEEDED"
export const API_V1_CATEGORY_CREATE_FAILED = "API_V1_CATEGORY_CREATE_FAILED"
export const API_V1_CATEGORY_READ = "API_V1_CATEGORY_READ"
export const API_V1_CATEGORY_READ_SUCCEEDED = "API_V1_CATEGORY_READ_SUCCEEDED"
export const API_V1_CATEGORY_READ_FAILED = "API_V1_CATEGORY_READ_FAILED"
export const API_V1_CATEGORY_UPDATE = "API_V1_CATEGORY_UPDATE"
export const API_V1_CATEGORY_UPDATE_SUCCEEDED =
  "API_V1_CATEGORY_UPDATE_SUCCEEDED"
export const API_V1_CATEGORY_UPDATE_FAILED = "API_V1_CATEGORY_UPDATE_FAILED"
export const API_V1_CATEGORY_PARTIAL_UPDATE = "API_V1_CATEGORY_PARTIAL_UPDATE"
export const API_V1_CATEGORY_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_CATEGORY_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_CATEGORY_PARTIAL_UPDATE_FAILED =
  "API_V1_CATEGORY_PARTIAL_UPDATE_FAILED"
export const API_V1_CATEGORY_DELETE = "API_V1_CATEGORY_DELETE"
export const API_V1_CATEGORY_DELETE_SUCCEEDED =
  "API_V1_CATEGORY_DELETE_SUCCEEDED"
export const API_V1_CATEGORY_DELETE_FAILED = "API_V1_CATEGORY_DELETE_FAILED"
export const API_V1_CUSTOMTEXT_LIST = "API_V1_CUSTOMTEXT_LIST"
export const API_V1_CUSTOMTEXT_LIST_SUCCEEDED =
  "API_V1_CUSTOMTEXT_LIST_SUCCEEDED"
export const API_V1_CUSTOMTEXT_LIST_FAILED = "API_V1_CUSTOMTEXT_LIST_FAILED"
export const API_V1_CUSTOMTEXT_READ = "API_V1_CUSTOMTEXT_READ"
export const API_V1_CUSTOMTEXT_READ_SUCCEEDED =
  "API_V1_CUSTOMTEXT_READ_SUCCEEDED"
export const API_V1_CUSTOMTEXT_READ_FAILED = "API_V1_CUSTOMTEXT_READ_FAILED"
export const API_V1_CUSTOMTEXT_UPDATE = "API_V1_CUSTOMTEXT_UPDATE"
export const API_V1_CUSTOMTEXT_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMTEXT_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMTEXT_UPDATE_FAILED = "API_V1_CUSTOMTEXT_UPDATE_FAILED"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE_FAILED =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE_FAILED"
export const API_V1_FAQ_LIST = "API_V1_FAQ_LIST"
export const API_V1_FAQ_LIST_SUCCEEDED = "API_V1_FAQ_LIST_SUCCEEDED"
export const API_V1_FAQ_LIST_FAILED = "API_V1_FAQ_LIST_FAILED"
export const API_V1_FAQ_CREATE = "API_V1_FAQ_CREATE"
export const API_V1_FAQ_CREATE_SUCCEEDED = "API_V1_FAQ_CREATE_SUCCEEDED"
export const API_V1_FAQ_CREATE_FAILED = "API_V1_FAQ_CREATE_FAILED"
export const API_V1_FAQ_READ = "API_V1_FAQ_READ"
export const API_V1_FAQ_READ_SUCCEEDED = "API_V1_FAQ_READ_SUCCEEDED"
export const API_V1_FAQ_READ_FAILED = "API_V1_FAQ_READ_FAILED"
export const API_V1_FAQ_UPDATE = "API_V1_FAQ_UPDATE"
export const API_V1_FAQ_UPDATE_SUCCEEDED = "API_V1_FAQ_UPDATE_SUCCEEDED"
export const API_V1_FAQ_UPDATE_FAILED = "API_V1_FAQ_UPDATE_FAILED"
export const API_V1_FAQ_PARTIAL_UPDATE = "API_V1_FAQ_PARTIAL_UPDATE"
export const API_V1_FAQ_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_FAQ_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_FAQ_PARTIAL_UPDATE_FAILED =
  "API_V1_FAQ_PARTIAL_UPDATE_FAILED"
export const API_V1_FAQ_DELETE = "API_V1_FAQ_DELETE"
export const API_V1_FAQ_DELETE_SUCCEEDED = "API_V1_FAQ_DELETE_SUCCEEDED"
export const API_V1_FAQ_DELETE_FAILED = "API_V1_FAQ_DELETE_FAILED"
export const API_V1_FAVORITES_LIST = "API_V1_FAVORITES_LIST"
export const API_V1_FAVORITES_LIST_SUCCEEDED = "API_V1_FAVORITES_LIST_SUCCEEDED"
export const API_V1_FAVORITES_LIST_FAILED = "API_V1_FAVORITES_LIST_FAILED"
export const API_V1_FAVORITES_CREATE = "API_V1_FAVORITES_CREATE"
export const API_V1_FAVORITES_CREATE_SUCCEEDED =
  "API_V1_FAVORITES_CREATE_SUCCEEDED"
export const API_V1_FAVORITES_CREATE_FAILED = "API_V1_FAVORITES_CREATE_FAILED"
export const API_V1_FAVORITES_READ = "API_V1_FAVORITES_READ"
export const API_V1_FAVORITES_READ_SUCCEEDED = "API_V1_FAVORITES_READ_SUCCEEDED"
export const API_V1_FAVORITES_READ_FAILED = "API_V1_FAVORITES_READ_FAILED"
export const API_V1_FAVORITES_UPDATE = "API_V1_FAVORITES_UPDATE"
export const API_V1_FAVORITES_UPDATE_SUCCEEDED =
  "API_V1_FAVORITES_UPDATE_SUCCEEDED"
export const API_V1_FAVORITES_UPDATE_FAILED = "API_V1_FAVORITES_UPDATE_FAILED"
export const API_V1_FAVORITES_PARTIAL_UPDATE = "API_V1_FAVORITES_PARTIAL_UPDATE"
export const API_V1_FAVORITES_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_FAVORITES_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_FAVORITES_PARTIAL_UPDATE_FAILED =
  "API_V1_FAVORITES_PARTIAL_UPDATE_FAILED"
export const API_V1_FAVORITES_DELETE = "API_V1_FAVORITES_DELETE"
export const API_V1_FAVORITES_DELETE_SUCCEEDED =
  "API_V1_FAVORITES_DELETE_SUCCEEDED"
export const API_V1_FAVORITES_DELETE_FAILED = "API_V1_FAVORITES_DELETE_FAILED"
export const API_V1_HOMEPAGE_LIST = "API_V1_HOMEPAGE_LIST"
export const API_V1_HOMEPAGE_LIST_SUCCEEDED = "API_V1_HOMEPAGE_LIST_SUCCEEDED"
export const API_V1_HOMEPAGE_LIST_FAILED = "API_V1_HOMEPAGE_LIST_FAILED"
export const API_V1_HOMEPAGE_READ = "API_V1_HOMEPAGE_READ"
export const API_V1_HOMEPAGE_READ_SUCCEEDED = "API_V1_HOMEPAGE_READ_SUCCEEDED"
export const API_V1_HOMEPAGE_READ_FAILED = "API_V1_HOMEPAGE_READ_FAILED"
export const API_V1_HOMEPAGE_UPDATE = "API_V1_HOMEPAGE_UPDATE"
export const API_V1_HOMEPAGE_UPDATE_SUCCEEDED =
  "API_V1_HOMEPAGE_UPDATE_SUCCEEDED"
export const API_V1_HOMEPAGE_UPDATE_FAILED = "API_V1_HOMEPAGE_UPDATE_FAILED"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE = "API_V1_HOMEPAGE_PARTIAL_UPDATE"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_HOMEPAGE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE_FAILED =
  "API_V1_HOMEPAGE_PARTIAL_UPDATE_FAILED"
export const API_V1_LOCATION_LIST = "API_V1_LOCATION_LIST"
export const API_V1_LOCATION_LIST_SUCCEEDED = "API_V1_LOCATION_LIST_SUCCEEDED"
export const API_V1_LOCATION_LIST_FAILED = "API_V1_LOCATION_LIST_FAILED"
export const API_V1_LOCATION_CREATE = "API_V1_LOCATION_CREATE"
export const API_V1_LOCATION_CREATE_SUCCEEDED =
  "API_V1_LOCATION_CREATE_SUCCEEDED"
export const API_V1_LOCATION_CREATE_FAILED = "API_V1_LOCATION_CREATE_FAILED"
export const API_V1_LOCATION_READ = "API_V1_LOCATION_READ"
export const API_V1_LOCATION_READ_SUCCEEDED = "API_V1_LOCATION_READ_SUCCEEDED"
export const API_V1_LOCATION_READ_FAILED = "API_V1_LOCATION_READ_FAILED"
export const API_V1_LOCATION_UPDATE = "API_V1_LOCATION_UPDATE"
export const API_V1_LOCATION_UPDATE_SUCCEEDED =
  "API_V1_LOCATION_UPDATE_SUCCEEDED"
export const API_V1_LOCATION_UPDATE_FAILED = "API_V1_LOCATION_UPDATE_FAILED"
export const API_V1_LOCATION_PARTIAL_UPDATE = "API_V1_LOCATION_PARTIAL_UPDATE"
export const API_V1_LOCATION_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_LOCATION_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_LOCATION_PARTIAL_UPDATE_FAILED =
  "API_V1_LOCATION_PARTIAL_UPDATE_FAILED"
export const API_V1_LOCATION_DELETE = "API_V1_LOCATION_DELETE"
export const API_V1_LOCATION_DELETE_SUCCEEDED =
  "API_V1_LOCATION_DELETE_SUCCEEDED"
export const API_V1_LOCATION_DELETE_FAILED = "API_V1_LOCATION_DELETE_FAILED"
export const API_V1_LOGIN_CREATE = "API_V1_LOGIN_CREATE"
export const API_V1_LOGIN_CREATE_SUCCEEDED = "API_V1_LOGIN_CREATE_SUCCEEDED"
export const API_V1_LOGIN_CREATE_FAILED = "API_V1_LOGIN_CREATE_FAILED"
export const API_V1_MYSCHEDULE_LIST = "API_V1_MYSCHEDULE_LIST"
export const API_V1_MYSCHEDULE_LIST_SUCCEEDED =
  "API_V1_MYSCHEDULE_LIST_SUCCEEDED"
export const API_V1_MYSCHEDULE_LIST_FAILED = "API_V1_MYSCHEDULE_LIST_FAILED"
export const API_V1_MYSCHEDULE_CREATE = "API_V1_MYSCHEDULE_CREATE"
export const API_V1_MYSCHEDULE_CREATE_SUCCEEDED =
  "API_V1_MYSCHEDULE_CREATE_SUCCEEDED"
export const API_V1_MYSCHEDULE_CREATE_FAILED = "API_V1_MYSCHEDULE_CREATE_FAILED"
export const API_V1_MYSCHEDULE_READ = "API_V1_MYSCHEDULE_READ"
export const API_V1_MYSCHEDULE_READ_SUCCEEDED =
  "API_V1_MYSCHEDULE_READ_SUCCEEDED"
export const API_V1_MYSCHEDULE_READ_FAILED = "API_V1_MYSCHEDULE_READ_FAILED"
export const API_V1_MYSCHEDULE_UPDATE = "API_V1_MYSCHEDULE_UPDATE"
export const API_V1_MYSCHEDULE_UPDATE_SUCCEEDED =
  "API_V1_MYSCHEDULE_UPDATE_SUCCEEDED"
export const API_V1_MYSCHEDULE_UPDATE_FAILED = "API_V1_MYSCHEDULE_UPDATE_FAILED"
export const API_V1_MYSCHEDULE_PARTIAL_UPDATE =
  "API_V1_MYSCHEDULE_PARTIAL_UPDATE"
export const API_V1_MYSCHEDULE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_MYSCHEDULE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_MYSCHEDULE_PARTIAL_UPDATE_FAILED =
  "API_V1_MYSCHEDULE_PARTIAL_UPDATE_FAILED"
export const API_V1_MYSCHEDULE_DELETE = "API_V1_MYSCHEDULE_DELETE"
export const API_V1_MYSCHEDULE_DELETE_SUCCEEDED =
  "API_V1_MYSCHEDULE_DELETE_SUCCEEDED"
export const API_V1_MYSCHEDULE_DELETE_FAILED = "API_V1_MYSCHEDULE_DELETE_FAILED"
export const API_V1_PRESENTER_LIST = "API_V1_PRESENTER_LIST"
export const API_V1_PRESENTER_LIST_SUCCEEDED = "API_V1_PRESENTER_LIST_SUCCEEDED"
export const API_V1_PRESENTER_LIST_FAILED = "API_V1_PRESENTER_LIST_FAILED"
export const API_V1_PRESENTER_CREATE = "API_V1_PRESENTER_CREATE"
export const API_V1_PRESENTER_CREATE_SUCCEEDED =
  "API_V1_PRESENTER_CREATE_SUCCEEDED"
export const API_V1_PRESENTER_CREATE_FAILED = "API_V1_PRESENTER_CREATE_FAILED"
export const API_V1_PRESENTER_READ = "API_V1_PRESENTER_READ"
export const API_V1_PRESENTER_READ_SUCCEEDED = "API_V1_PRESENTER_READ_SUCCEEDED"
export const API_V1_PRESENTER_READ_FAILED = "API_V1_PRESENTER_READ_FAILED"
export const API_V1_PRESENTER_UPDATE = "API_V1_PRESENTER_UPDATE"
export const API_V1_PRESENTER_UPDATE_SUCCEEDED =
  "API_V1_PRESENTER_UPDATE_SUCCEEDED"
export const API_V1_PRESENTER_UPDATE_FAILED = "API_V1_PRESENTER_UPDATE_FAILED"
export const API_V1_PRESENTER_PARTIAL_UPDATE = "API_V1_PRESENTER_PARTIAL_UPDATE"
export const API_V1_PRESENTER_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_PRESENTER_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_PRESENTER_PARTIAL_UPDATE_FAILED =
  "API_V1_PRESENTER_PARTIAL_UPDATE_FAILED"
export const API_V1_PRESENTER_DELETE = "API_V1_PRESENTER_DELETE"
export const API_V1_PRESENTER_DELETE_SUCCEEDED =
  "API_V1_PRESENTER_DELETE_SUCCEEDED"
export const API_V1_PRESENTER_DELETE_FAILED = "API_V1_PRESENTER_DELETE_FAILED"
export const API_V1_SCHEDULE_LIST = "API_V1_SCHEDULE_LIST"
export const API_V1_SCHEDULE_LIST_SUCCEEDED = "API_V1_SCHEDULE_LIST_SUCCEEDED"
export const API_V1_SCHEDULE_LIST_FAILED = "API_V1_SCHEDULE_LIST_FAILED"
export const API_V1_SCHEDULE_CREATE = "API_V1_SCHEDULE_CREATE"
export const API_V1_SCHEDULE_CREATE_SUCCEEDED =
  "API_V1_SCHEDULE_CREATE_SUCCEEDED"
export const API_V1_SCHEDULE_CREATE_FAILED = "API_V1_SCHEDULE_CREATE_FAILED"
export const API_V1_SCHEDULE_READ = "API_V1_SCHEDULE_READ"
export const API_V1_SCHEDULE_READ_SUCCEEDED = "API_V1_SCHEDULE_READ_SUCCEEDED"
export const API_V1_SCHEDULE_READ_FAILED = "API_V1_SCHEDULE_READ_FAILED"
export const API_V1_SCHEDULE_UPDATE = "API_V1_SCHEDULE_UPDATE"
export const API_V1_SCHEDULE_UPDATE_SUCCEEDED =
  "API_V1_SCHEDULE_UPDATE_SUCCEEDED"
export const API_V1_SCHEDULE_UPDATE_FAILED = "API_V1_SCHEDULE_UPDATE_FAILED"
export const API_V1_SCHEDULE_PARTIAL_UPDATE = "API_V1_SCHEDULE_PARTIAL_UPDATE"
export const API_V1_SCHEDULE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_SCHEDULE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_SCHEDULE_PARTIAL_UPDATE_FAILED =
  "API_V1_SCHEDULE_PARTIAL_UPDATE_FAILED"
export const API_V1_SCHEDULE_DELETE = "API_V1_SCHEDULE_DELETE"
export const API_V1_SCHEDULE_DELETE_SUCCEEDED =
  "API_V1_SCHEDULE_DELETE_SUCCEEDED"
export const API_V1_SCHEDULE_DELETE_FAILED = "API_V1_SCHEDULE_DELETE_FAILED"
export const API_V1_SIGNUP_CREATE = "API_V1_SIGNUP_CREATE"
export const API_V1_SIGNUP_CREATE_SUCCEEDED = "API_V1_SIGNUP_CREATE_SUCCEEDED"
export const API_V1_SIGNUP_CREATE_FAILED = "API_V1_SIGNUP_CREATE_FAILED"
export const API_V1_SPONSOR_LIST = "API_V1_SPONSOR_LIST"
export const API_V1_SPONSOR_LIST_SUCCEEDED = "API_V1_SPONSOR_LIST_SUCCEEDED"
export const API_V1_SPONSOR_LIST_FAILED = "API_V1_SPONSOR_LIST_FAILED"
export const API_V1_SPONSOR_CREATE = "API_V1_SPONSOR_CREATE"
export const API_V1_SPONSOR_CREATE_SUCCEEDED = "API_V1_SPONSOR_CREATE_SUCCEEDED"
export const API_V1_SPONSOR_CREATE_FAILED = "API_V1_SPONSOR_CREATE_FAILED"
export const API_V1_SPONSOR_READ = "API_V1_SPONSOR_READ"
export const API_V1_SPONSOR_READ_SUCCEEDED = "API_V1_SPONSOR_READ_SUCCEEDED"
export const API_V1_SPONSOR_READ_FAILED = "API_V1_SPONSOR_READ_FAILED"
export const API_V1_SPONSOR_UPDATE = "API_V1_SPONSOR_UPDATE"
export const API_V1_SPONSOR_UPDATE_SUCCEEDED = "API_V1_SPONSOR_UPDATE_SUCCEEDED"
export const API_V1_SPONSOR_UPDATE_FAILED = "API_V1_SPONSOR_UPDATE_FAILED"
export const API_V1_SPONSOR_PARTIAL_UPDATE = "API_V1_SPONSOR_PARTIAL_UPDATE"
export const API_V1_SPONSOR_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_SPONSOR_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_SPONSOR_PARTIAL_UPDATE_FAILED =
  "API_V1_SPONSOR_PARTIAL_UPDATE_FAILED"
export const API_V1_SPONSOR_DELETE = "API_V1_SPONSOR_DELETE"
export const API_V1_SPONSOR_DELETE_SUCCEEDED = "API_V1_SPONSOR_DELETE_SUCCEEDED"
export const API_V1_SPONSOR_DELETE_FAILED = "API_V1_SPONSOR_DELETE_FAILED"
export const API_V1_VENDOR_LIST = "API_V1_VENDOR_LIST"
export const API_V1_VENDOR_LIST_SUCCEEDED = "API_V1_VENDOR_LIST_SUCCEEDED"
export const API_V1_VENDOR_LIST_FAILED = "API_V1_VENDOR_LIST_FAILED"
export const API_V1_VENDOR_CREATE = "API_V1_VENDOR_CREATE"
export const API_V1_VENDOR_CREATE_SUCCEEDED = "API_V1_VENDOR_CREATE_SUCCEEDED"
export const API_V1_VENDOR_CREATE_FAILED = "API_V1_VENDOR_CREATE_FAILED"
export const API_V1_VENDOR_READ = "API_V1_VENDOR_READ"
export const API_V1_VENDOR_READ_SUCCEEDED = "API_V1_VENDOR_READ_SUCCEEDED"
export const API_V1_VENDOR_READ_FAILED = "API_V1_VENDOR_READ_FAILED"
export const API_V1_VENDOR_UPDATE = "API_V1_VENDOR_UPDATE"
export const API_V1_VENDOR_UPDATE_SUCCEEDED = "API_V1_VENDOR_UPDATE_SUCCEEDED"
export const API_V1_VENDOR_UPDATE_FAILED = "API_V1_VENDOR_UPDATE_FAILED"
export const API_V1_VENDOR_PARTIAL_UPDATE = "API_V1_VENDOR_PARTIAL_UPDATE"
export const API_V1_VENDOR_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_VENDOR_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_VENDOR_PARTIAL_UPDATE_FAILED =
  "API_V1_VENDOR_PARTIAL_UPDATE_FAILED"
export const API_V1_VENDOR_DELETE = "API_V1_VENDOR_DELETE"
export const API_V1_VENDOR_DELETE_SUCCEEDED = "API_V1_VENDOR_DELETE_SUCCEEDED"
export const API_V1_VENDOR_DELETE_FAILED = "API_V1_VENDOR_DELETE_FAILED"
export const API_V1_VENDORDETAIL_LIST = "API_V1_VENDORDETAIL_LIST"
export const API_V1_VENDORDETAIL_LIST_SUCCEEDED =
  "API_V1_VENDORDETAIL_LIST_SUCCEEDED"
export const API_V1_VENDORDETAIL_LIST_FAILED = "API_V1_VENDORDETAIL_LIST_FAILED"
export const API_V1_VENDORDETAIL_CREATE = "API_V1_VENDORDETAIL_CREATE"
export const API_V1_VENDORDETAIL_CREATE_SUCCEEDED =
  "API_V1_VENDORDETAIL_CREATE_SUCCEEDED"
export const API_V1_VENDORDETAIL_CREATE_FAILED =
  "API_V1_VENDORDETAIL_CREATE_FAILED"
export const API_V1_VENDORDETAIL_READ = "API_V1_VENDORDETAIL_READ"
export const API_V1_VENDORDETAIL_READ_SUCCEEDED =
  "API_V1_VENDORDETAIL_READ_SUCCEEDED"
export const API_V1_VENDORDETAIL_READ_FAILED = "API_V1_VENDORDETAIL_READ_FAILED"
export const API_V1_VENDORDETAIL_UPDATE = "API_V1_VENDORDETAIL_UPDATE"
export const API_V1_VENDORDETAIL_UPDATE_SUCCEEDED =
  "API_V1_VENDORDETAIL_UPDATE_SUCCEEDED"
export const API_V1_VENDORDETAIL_UPDATE_FAILED =
  "API_V1_VENDORDETAIL_UPDATE_FAILED"
export const API_V1_VENDORDETAIL_PARTIAL_UPDATE =
  "API_V1_VENDORDETAIL_PARTIAL_UPDATE"
export const API_V1_VENDORDETAIL_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_VENDORDETAIL_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_VENDORDETAIL_PARTIAL_UPDATE_FAILED =
  "API_V1_VENDORDETAIL_PARTIAL_UPDATE_FAILED"
export const API_V1_VENDORDETAIL_DELETE = "API_V1_VENDORDETAIL_DELETE"
export const API_V1_VENDORDETAIL_DELETE_SUCCEEDED =
  "API_V1_VENDORDETAIL_DELETE_SUCCEEDED"
export const API_V1_VENDORDETAIL_DELETE_FAILED =
  "API_V1_VENDORDETAIL_DELETE_FAILED"
export const REST_AUTH_LOGIN_CREATE = "REST_AUTH_LOGIN_CREATE"
export const REST_AUTH_LOGIN_CREATE_SUCCEEDED =
  "REST_AUTH_LOGIN_CREATE_SUCCEEDED"
export const REST_AUTH_LOGIN_CREATE_FAILED = "REST_AUTH_LOGIN_CREATE_FAILED"
export const REST_AUTH_LOGOUT_LIST = "REST_AUTH_LOGOUT_LIST"
export const REST_AUTH_LOGOUT_LIST_SUCCEEDED = "REST_AUTH_LOGOUT_LIST_SUCCEEDED"
export const REST_AUTH_LOGOUT_LIST_FAILED = "REST_AUTH_LOGOUT_LIST_FAILED"
export const REST_AUTH_LOGOUT_CREATE = "REST_AUTH_LOGOUT_CREATE"
export const REST_AUTH_LOGOUT_CREATE_SUCCEEDED =
  "REST_AUTH_LOGOUT_CREATE_SUCCEEDED"
export const REST_AUTH_LOGOUT_CREATE_FAILED = "REST_AUTH_LOGOUT_CREATE_FAILED"
export const REST_AUTH_PASSWORD_CHANGE_CREATE =
  "REST_AUTH_PASSWORD_CHANGE_CREATE"
export const REST_AUTH_PASSWORD_CHANGE_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_CHANGE_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_CHANGE_CREATE_FAILED =
  "REST_AUTH_PASSWORD_CHANGE_CREATE_FAILED"
export const REST_AUTH_PASSWORD_RESET_CREATE = "REST_AUTH_PASSWORD_RESET_CREATE"
export const REST_AUTH_PASSWORD_RESET_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_RESET_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_RESET_CREATE_FAILED =
  "REST_AUTH_PASSWORD_RESET_CREATE_FAILED"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_FAILED =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_FAILED"
export const REST_AUTH_REGISTRATION_CREATE = "REST_AUTH_REGISTRATION_CREATE"
export const REST_AUTH_REGISTRATION_CREATE_SUCCEEDED =
  "REST_AUTH_REGISTRATION_CREATE_SUCCEEDED"
export const REST_AUTH_REGISTRATION_CREATE_FAILED =
  "REST_AUTH_REGISTRATION_CREATE_FAILED"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_SUCCEEDED =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_SUCCEEDED"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_FAILED =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_FAILED"
export const REST_AUTH_USER_READ = "REST_AUTH_USER_READ"
export const REST_AUTH_USER_READ_SUCCEEDED = "REST_AUTH_USER_READ_SUCCEEDED"
export const REST_AUTH_USER_READ_FAILED = "REST_AUTH_USER_READ_FAILED"
export const REST_AUTH_USER_UPDATE = "REST_AUTH_USER_UPDATE"
export const REST_AUTH_USER_UPDATE_SUCCEEDED = "REST_AUTH_USER_UPDATE_SUCCEEDED"
export const REST_AUTH_USER_UPDATE_FAILED = "REST_AUTH_USER_UPDATE_FAILED"
export const REST_AUTH_USER_PARTIAL_UPDATE = "REST_AUTH_USER_PARTIAL_UPDATE"
export const REST_AUTH_USER_PARTIAL_UPDATE_SUCCEEDED =
  "REST_AUTH_USER_PARTIAL_UPDATE_SUCCEEDED"
export const REST_AUTH_USER_PARTIAL_UPDATE_FAILED =
  "REST_AUTH_USER_PARTIAL_UPDATE_FAILED"
